### ISSUE TITLE
This project has misleading name

### ISSUE THREAD

**Issue by pbortlov** [fedora-modularity/message-tagging-service#80] opened 2020-01-08 14:13 UTC
Hi,

I was searching for the rhmsg library and got to this project where I was really confused what this project does because OSBS team has a project (Gutentag @lkolacek) for tagging images but the name of this project is so similar that I really had to ask @csomh what is this project about and if the project is not similar to Gutentag. Is it possible to change the name to something more descriptive (@csomh suggested **module-tagging-service**)?

Thank you

**Comment by lcarva** [comment] 2020-01-09 15:15
This is a duplicate of #34.

**Closed by lcarva** 2020-01-09 15:15 UTC
